# Funding
# If you find this project useful, consider supporting its development:

# Crypto wallet (ETH/BNB/Polygon/Arbitrum/Base)
custom:
  - https://etherscan.io/address/0x051BF9b67aC43BbB461A33E13c21218f304E31BB
